name: Docker Build and Release
on: [ push ]
env:
  #### An dieser Stelle müssen eure persönlichen Umgebungsvariablen eingetragen werden
  # Tipp: Die Token/der API-Key werden als Secrets in den Repository-Settings eingetragen und hier referenziert.
  # Test
  ACCESSTOKEN: ${{ secrets.ACCESSTOKEN }}
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Compile, build and push
        run: |
          ./mvnw package
          docker build --tag ghcr.io/zakiroov/pet-clinic:latest -f Dockerfile .
          docker login --username zakiroov --password $ACCESSTOKEN ghcr.io
          docker push ghcr.io/zakiroov/pet-clinic:latest
